In [1]:
#Import Library
import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta

np.random.seed(69)
random.seed(69)

n_asli = 100 # Data asli pas 100

# 1. List manual ben gak butuh Faker
nama_list = ['Budi', 'Ani', 'Citra', 'Doni', 'Eka', 'Fajar', 'Gina', 'Hadi', 'Indah', 'Joko',
             'Kiki', 'Lina', 'Mamat', 'Nia', 'Oki', 'Putri', 'Qori', 'Rina', 'Sari', 'Tono']
kelas_list = ['7a', '7A ', '8b', '8B', ' 9c', '9C']
gender_list = ['L', 'Laki-laki', 'P', 'Perempuan ', ' laki-laki', 'perempuan']
ekskul_list = ['Pramuka', 'pramuka ', 'Bola', 'BOLA', 'Seni', np.nan]

# Fungsi buat tanggal acak
def random_date_awur():
    start_date = datetime(2007, 1, 1) # Umur 11-18 thn dari 2025
    end_date = datetime(2014, 12, 31)
    random_days = random.randint(0, (end_date - start_date).days)
    tgl = start_date + timedelta(days=random_days)
    format_tgl = random.choice(['%Y-%m-%d', '%d/%m/%Y', '%m-%d-%Y', '%d %b %Y'])
    return tgl.strftime(format_tgl)

# 2. Bikin data asli sengaja kotor
data = {
    'nis': np.arange(1001, 1001+n_asli),
    'nama_siswa': [random.choice(nama_list).upper() if i%4==0 else random.choice(nama_list).lower() for i in range(n_asli)],
    'jenis_kelamin': np.random.choice(gender_list, n_asli),
    'umur': list(np.random.randint(11, 18, size=n_asli-3)) + [5, 150, 25], # 97 normal + 3 outlier
    'kelas': np.random.choice(kelas_list, n_asli),
    'nilai_matematika': np.random.randint(40, 100, size=n_asli).astype(float),
    'ekstrakurikuler': np.random.choice(ekskul_list, n_asli),
    'tanggal_lahir': [random_date_awur() for _ in range(n_asli)]
}

df_asli = pd.DataFrame(data)

# 3. Bikin `nilai_matematika` kosong dan & 0
df_asli.loc[np.random.choice(df_asli.index, 7, replace=False), 'nilai_matematika'] = np.nan
df_asli.loc[np.random.choice(df_asli.index, 3, replace=False), 'nilai_matematika'] = 0

# 4. BIKIN DUPLIKAT 5 BARIS saja
df_duplikat = df_asli.sample(5, random_state=1)
#df_duplikat['nis'] = df_duplikat['nis'] + 10000 # Biar NIS ne beda

# 5. Gabungkan + Acak
df = pd.concat([df_asli, df_duplikat], ignore_index=True)
df = df.sample(frac=1, random_state=2).reset_index(drop=True)

# 6. Save jadi CSV
df.to_csv('data_siswa_kotor_105.csv', index=False)
print(f"Berhasil! Total baris: {len(df)} -> 100 Asli + 5 Duplikat")
print(df.head(10))

Berhasil! Total baris: 105 -> 100 Asli + 5 Duplikat
    nis nama_siswa jenis_kelamin  umur kelas  nilai_matematika  \
0  1080       rina     Laki-laki    14   7A               79.0
1  1075      putri     perempuan    17    8b              52.0
2  1062      mamat             L    12    8b              56.0
3  1028       joko     laki-laki    11    8B              56.0
4  1017       RINA     perempuan    17    8B              67.0
5  1025        EKA     Laki-laki    14    9C              78.0
6  1003      fajar    Perempuan     11    8b              76.0
7  1029       GINA    Perempuan     12    7a              41.0
8  1030       qori    Perempuan     12    9c              89.0
9  1014       qori             P    13    7a              68.0

  ekstrakurikuler tanggal_lahir
0        pramuka    12 Aug 2014
1            BOLA    05-21-2008
2             nan    08/11/2012
3             nan    05-27-2013
4            Bola    2009-09-08
5        pramuka     2013-06-09
6         Pramuka    2013-02-19
7            BOLA    2007-02-20
8            Seni   04 Feb 2013
9        pramuka    11 May 2008

In [2]:
#Tampilan Data Acak
df

,nis,nama_siswa,jenis_kelamin,umur,kelas,nilai_matematika,ekstrakurikuler,tanggal_lahir
0,1080,rina,Laki-laki,14,7A,79.0,pramuka,12 Aug 2014
1,1075,putri,perempuan,17,8b,52.0,BOLA,05-21-2008
2,1062,mamat,L,12,8b,56.0,nan,08/11/2012
3,1028,joko,laki-laki,11,8B,56.0,nan,05-27-2013
4,1017,RINA,perempuan,17,8B,67.0,Bola,2009-09-08
...,...,...,...,...,...,...,...,...
100,1044,budi,P,12,7a,66.0,BOLA,03-11-2009
101,1023,nia,L,16,8B,93.0,BOLA,03-29-2008
102,1073,INDAH,P,12,7a,85.0,nan,27 Jun 2008
103,1016,rina,Perempuan,14,8b,64.0,pramuka,06 Dec 2013
104,1041,CITRA,perempuan,12,8B,46.0,BOLA,2010-06-07

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105 entries, 0 to 104
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   nis               105 non-null    int64
 1   nama_siswa        105 non-null    object
 2   jenis_kelamin     105 non-null    object
 3   umur              105 non-null    int64
 4   kelas             105 non-null    object
 5   nilai_matematika  98 non-null     float64
 6   ekstrakurikuler   105 non-null    object
 7   tanggal_lahir     105 non-null    object
dtypes: float64(1), int64(2), object(5)
memory usage: 6.7+ KB

In [4]:
df['tanggal_lahir'].unique()

array(['12 Aug 2014', '05-21-2008', '08/11/2012', '05-27-2013',
       '2009-09-08', '2013-06-09', '2013-02-19', '2007-02-20',
       '04 Feb 2013', '11 May 2008', '08 Oct 2012', '03-22-2007',
       '2014-05-29', '04-30-2011', '2008-09-13', '07/02/2010',
       '06 Aug 2012', '04-13-2010', '2009-12-17', '2008-02-01',
       '04-27-2009', '14 Jul 2008', '19/06/2007', '23/10/2007',
       '03-27-2010', '21 Apr 2009', '10-26-2013', '2012-06-08',
       '09/06/2013', '28 Dec 2008', '24/01/2011', '12/10/2007',
       '2010-03-12', '2010-03-27', '2014-05-21', '10/09/2011',
       '2010-04-27', '2007-12-06', '06-04-2009', '2007-04-10',
       '2010-12-21', '15 Mar 2011', '03 Nov 2014', '06-28-2013',
       '08-03-2009', '2011-01-25', '18/01/2010', '02-29-2008',
       '13 May 2012', '2014-11-06', '02-18-2013', '02-14-2008',
       '02-18-2012', '2014-09-01', '12-04-2008', '2008-10-02',
       '21/12/2007', '18/12/2011', '2009-11-13', '2011-06-29',
       '06 Jul 2012', '03-23-2008', '2013-03-26', '05-17-2007',
       '24 Mar 2014', '2010-03-03', '2010-01-28', '02-06-2008',
       '2012-06-30', '10-06-2009', '01/04/2008', '31/12/2011',
       '04-29-2010', '2009-12-05', '07/10/2010', '11-18-2013',
       '05 Aug 2008', '02-23-2012', '03-09-2012', '07-23-2008',
       '30/07/2013', '26 Dec 2011', '05-07-2011', '10/09/2010',
       '10/03/2014', '05-08-2011', '28/06/2010', '22 Aug 2008',
       '03 Feb 2007', '2007-02-04', '11/10/2010', '18 Nov 2012',
       '27/05/2011', '07 May 2010', '2013-01-09', '03-11-2009',
       '03-29-2008', '27 Jun 2008', '06 Dec 2013', '2010-06-07'],
      dtype=object)

In [5]:
#Standardisasi Format Tanggal Lahir

df['tanggal_lahir'] = pd.to_datetime(
    df['tanggal_lahir'],
    format='mixed',
    errors='coerce'
)

print(df['tanggal_lahir'].dtype)

datetime64[ns]

In [6]:
df

,nis,nama_siswa,jenis_kelamin,umur,kelas,nilai_matematika,ekstrakurikuler,tanggal_lahir
0,1080,rina,Laki-laki,14,7A,79.0,pramuka,2014-08-12
1,1075,putri,perempuan,17,8b,52.0,BOLA,2008-05-21
2,1062,mamat,L,12,8b,56.0,nan,2012-08-11
3,1028,joko,laki-laki,11,8B,56.0,nan,2013-05-27
4,1017,RINA,perempuan,17,8B,67.0,Bola,2009-09-08
...,...,...,...,...,...,...,...,...
100,1044,budi,P,12,7a,66.0,BOLA,2009-03-11
101,1023,nia,L,16,8B,93.0,BOLA,2008-03-29
102,1073,INDAH,P,12,7a,85.0,nan,2008-06-27
103,1016,rina,Perempuan,14,8b,64.0,pramuka,2013-12-06
104,1041,CITRA,perempuan,12,8B,46.0,BOLA,2010-06-07

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105 entries, 0 to 104
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   nis               105 non-null    int64
 1   nama_siswa        105 non-null    object
 2   jenis_kelamin     105 non-null    object
 3   umur              105 non-null    int64
 4   kelas             105 non-null    object
 5   nilai_matematika  98 non-null     float64
 6   ekstrakurikuler   105 non-null    object
 7   tanggal_lahir     105 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(2), object(4)
memory usage: 6.7+ KB

In [8]:
#Standardisasi Kata Tiap Kolom

#nama_siswa Besar Awal Saja
df['nama_siswa']=df['nama_siswa'].str.lower().str.strip().str.title()

#Jenis Kelamin
#Hilangkan spasi dan ubah ke huruf kecil
df['jenis_kelamin'] = df['jenis_kelamin'].str.strip().str.lower()

# Mapping ke format yang sama
df['jenis_kelamin'] = df['jenis_kelamin'].replace({
    'l': 'Laki-laki',
    'laki-laki': 'Laki-laki',
    'p': 'Perempuan',
    'perempuan': 'Perempuan'
})

# Kelas menjadi Huruf Besar
df['kelas']=df['kelas'].str.upper().str.strip()

#Ekskul Huruf Besar Awal Saja
df['ekstrakurikuler']=df['ekstrakurikuler'].str.lower().str.strip().str.title()

In [9]:
df

,nis,nama_siswa,jenis_kelamin,umur,kelas,nilai_matematika,ekstrakurikuler,tanggal_lahir
0,1080,Rina,Laki-laki,14,7A,79.0,Pramuka,2014-08-12
1,1075,Putri,Perempuan,17,8B,52.0,Bola,2008-05-21
2,1062,Mamat,Laki-laki,12,8B,56.0,Nan,2012-08-11
3,1028,Joko,Laki-laki,11,8B,56.0,Nan,2013-05-27
4,1017,Rina,Perempuan,17,8B,67.0,Bola,2009-09-08
...,...,...,...,...,...,...,...,...
100,1044,Budi,Perempuan,12,7A,66.0,Bola,2009-03-11
101,1023,Nia,Laki-laki,16,8B,93.0,Bola,2008-03-29
102,1073,Indah,Perempuan,12,7A,85.0,Nan,2008-06-27
103,1016,Rina,Perempuan,14,8B,64.0,Pramuka,2013-12-06
104,1041,Citra,Perempuan,12,8B,46.0,Bola,2010-06-07

In [10]:
#handle missing value
#nilai mtk kosong diisi Rerata
df['nilai_matematika']=df['nilai_matematika'].fillna(df['nilai_matematika'].mean())

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105 entries, 0 to 104
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   nis               105 non-null    int64
 1   nama_siswa        105 non-null    object
 2   jenis_kelamin     105 non-null    object
 3   umur              105 non-null    int64
 4   kelas             105 non-null    object
 5   nilai_matematika  105 non-null    float64
 6   ekstrakurikuler   105 non-null    object
 7   tanggal_lahir     105 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(2), object(4)
memory usage: 6.7+ KB

In [12]:
#Handle duplikat data
df.duplicated().sum()

np.int64(5)

In [13]:
df_final=df.drop_duplicates().reset_index(drop=True)
df_final

,nis,nama_siswa,jenis_kelamin,umur,kelas,nilai_matematika,ekstrakurikuler,tanggal_lahir
0,1080,Rina,Laki-laki,14,7A,79.0,Pramuka,2014-08-12
1,1075,Putri,Perempuan,17,8B,52.0,Bola,2008-05-21
2,1062,Mamat,Laki-laki,12,8B,56.0,Nan,2012-08-11
3,1028,Joko,Laki-laki,11,8B,56.0,Nan,2013-05-27
4,1017,Rina,Perempuan,17,8B,67.0,Bola,2009-09-08
...,...,...,...,...,...,...,...,...
95,1044,Budi,Perempuan,12,7A,66.0,Bola,2009-03-11
96,1023,Nia,Laki-laki,16,8B,93.0,Bola,2008-03-29
97,1073,Indah,Perempuan,12,7A,85.0,Nan,2008-06-27
98,1016,Rina,Perempuan,14,8B,64.0,Pramuka,2013-12-06
99,1041,Citra,Perempuan,12,8B,46.0,Bola,2010-06-07

In [14]:
df_final

,nis,nama_siswa,jenis_kelamin,umur,kelas,nilai_matematika,ekstrakurikuler,tanggal_lahir
0,1080,Rina,Laki-laki,14,7A,79.0,Pramuka,2014-08-12
1,1075,Putri,Perempuan,17,8B,52.0,Bola,2008-05-21
2,1062,Mamat,Laki-laki,12,8B,56.0,Nan,2012-08-11
3,1028,Joko,Laki-laki,11,8B,56.0,Nan,2013-05-27
4,1017,Rina,Perempuan,17,8B,67.0,Bola,2009-09-08
...,...,...,...,...,...,...,...,...
95,1044,Budi,Perempuan,12,7A,66.0,Bola,2009-03-11
96,1023,Nia,Laki-laki,16,8B,93.0,Bola,2008-03-29
97,1073,Indah,Perempuan,12,7A,85.0,Nan,2008-06-27
98,1016,Rina,Perempuan,14,8B,64.0,Pramuka,2013-12-06
99,1041,Citra,Perempuan,12,8B,46.0,Bola,2010-06-07